name: Playwright Tests
on:
  push:
    branches: -main
  pull_request:
    branches: -main

jobs:
  test:
    runs-on: ubuntu-latest #macos-latest, windows-latest
    strategy:
      matrix:
        browser: [chromium]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2

      - name: Install dependencies
        run: npm ci

      - name: Run Playwright Tests
        run: npm run test:smoke

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
