name: Playwright Online Shop Tests
on:
  push:
    branches: -main
  pull_request:
    branches: -main
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tests/e2e/home.spec.ts

    # strategy:
    #   matrix:
    #     nodejs-version: [18.12.1]
    env:
      MODE: 'dev'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright Tests
        run: npx playwright test -g @smoke
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 5
