name: Playwright E2E tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: install dependencies
        run: npm ci
      - name: install Playwright browsers
        run: npx playwright install --with-deps
      - run: echo "Hello $USER"
        env:
          USER: ${{ vars.USER }}
          USER_EMAIL: ${{ vars.USER_EMAIL }}
          USER_PASSWORD: ${{ vars.USER_PASSWORD }}
          USER_API: ${{ vars.USER_API }}
          USER_API_EMAIL: ${{ vars.USER_API_EMAIL }}
      - name: run Playwright tests
        run: npx playwright test --grep @smoke
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7
